name: Deploy Belva to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker build -t startupbelva:latest .
        docker tag startupbelva:latest linusmatola/startupbelva:latest
        docker push linusmatola/startupbelva:latest

  deploy:
    needs: build
    runs-on: belva-runner

    steps:
    - name: SSH into EC2 and deploy Docker container
      run: |
        docker pull linusmatola/startupbelva:latest
        docker stop startupbelva || true
        docker rm startupbelva || true
        docker run -d -p 80:3000 --name startupbelva linusmatola/startupbelva:latest
