name: Next Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t linusmatola/startupbelva .

      - name: Publish Image to Docker Hub
        run: docker push linusmatola/startupbelva:latest

  deploy:
    needs: build
    # runs-on: aws-ec2
    runs-on: belva-runner

    steps:
      - name: Check sudo privileges
        run: sudo whoami

      - name: Add user to Docker group
        run: sudo usermod -aG docker $USER

      - name: Restart Docker service
        run: sudo service docker restart

      - name: Login to Docker Hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from Docker Hub
        run: sudo docker pull linusmatola/startupbelva:latest

      - name: Delete Old Container
        run: sudo docker rm -f belvaContainer || true

      - name: Run Docker container
        run: sudo docker run -d -p 5050:80 --name belvaContainer linusmatola/startupbelva:latest
